export const PROJECTS = [
  {
    id: 'iam',
    title: 'IAM Legal Expert',
    type: 'RAG + Knowledge Graph Platform',
    desc: 'An AI-powered legal domain expert built for a government Department of Infrastructure. Lets users ask plain-English questions about South African asset management legislation and standards, and returns structured, source-cited answers drawn from a curated document corpus.',
    tech: ['React', 'Neo4j', 'PGVector', 'LangChain', 'spaCy', 'Terraform', 'Azure'],
    color: '#f472b6',
    shape: 'octahedron',
    overview: 'Designed and built largely solo for the Western Cape Department of Infrastructure. The platform allows staff to query complex South African asset management legislation, ISO standards, and government frameworks through a conversational interface — replacing manual document searches with a cited, intelligent assistant.',
    architecture: [
      { label: 'React SPA', detail: 'Conversational chat interface with document filtering, date-range controls, adjustable retrieval settings, knowledge graph visualisation, and export to PDF or Word.' },
      { label: 'Node.js API Gateway', detail: 'Secure Express.js gateway handling authentication, request validation, rate limiting, and routing between the frontend and backend services.' },
      { label: 'Python RAG Backend', detail: 'Core intelligence layer built with Flask and LangChain. Orchestrates vector search, entity recognition, knowledge graph lookups, and LLM generation in a multi-step pipeline.' },
      { label: 'Knowledge Graph Service', detail: 'Dedicated service combining Neo4j Enterprise with a PDF processing pipeline — extracting entities and relationships from legal documents and building a queryable graph.' },
    ],
    highlights: [
      { title: 'End-to-End RAG Pipeline', text: 'Built a multi-step retrieval pipeline that combines semantic vector search with knowledge graph traversal. Queries are enriched with related entities before being passed to an LLM, producing answers with source citations and confidence indicators.' },
      { title: 'Neo4j Knowledge Graph', text: 'Designed and implemented a knowledge graph that maps entities and relationships across 14 government and ISO documents. The graph powers contextual enrichment during queries and is exposed as an interactive visualisation in the UI.' },
      { title: 'Full Azure Infrastructure via Terraform', text: 'Sole author of the entire cloud infrastructure — provisioned using Terraform across development, staging, and production environments. Includes private networking, containerised workloads, managed databases, AI services, document storage, and CI/CD pipelines.' },
      { title: 'Automated Document Ingestion', text: 'Built a pipeline that downloads PDFs from cloud storage, extracts and chunks text, runs named entity recognition, identifies relationships, and stores structured data into both the vector store and knowledge graph.' },
      { title: 'Secure Multi-Service Architecture', text: 'Implemented end-to-end security using Microsoft Entra ID for user authentication and Azure Managed Identity for service-to-service communication — eliminating hardcoded credentials across all services.' },
      { title: 'CI/CD Across All Services', text: 'Authored Azure DevOps pipelines for every component, automating Docker builds, container registry pushes, and staged deployments with manual approval gates between environments.' },
    ],
    security: ['Private VNet isolating all backend services', 'Microsoft Entra ID JWT authentication for all users', 'Azure Managed Identity for passwordless service auth', 'No public access to databases — private endpoints only', 'Environment-gated deployments (dev → staging approval)', 'SSH-restricted jumpbox for secure operational access'],
  },
  {
    id: 'camp',
    title: 'C-AMP AI Business Intelligence',
    type: 'AI-Powered Analytics Platform',
    desc: 'A natural-language business intelligence system built for the Western Cape Government. Users ask questions about government facility data in plain English and receive interactive charts, data tables, and AI-written business interpretations — no SQL knowledge required.',
    tech: ['React', 'FastAPI', 'LangGraph', 'PostgreSQL', 'Plotly', 'Docker', 'Azure'],
    color: '#6c63ff',
    shape: 'torus-knot',
    overview: 'Built collaboratively for the Western Cape Government\'s Department of Infrastructure. The system democratises access to complex government facility data — allowing non-technical staff to ask business questions and receive charts, tables, and written interpretations instantly, without writing a single line of SQL.',
    architecture: [
      { label: 'React Frontend', detail: 'Single-page application with interactive Plotly chart rendering, model selection, interpretation mode toggle, and conversation context for follow-up questions.' },
      { label: 'Node.js API Gateway', detail: 'Secure Express.js proxy with Azure Entra ID JWT authentication, OpenAPI contract validation, rate limiting, and auto-generated API documentation.' },
      { label: 'FastAPI + LangGraph Backend', detail: 'Multi-agent orchestration layer that routes questions, generates SQL, executes queries, selects the appropriate chart type, and produces AI-written business interpretations.' },
      { label: 'Database Layer', detail: 'Structured government facility dataset covering asset conditions, lifecycle data, financial summaries, and performance metrics — used in both development and production environments.' },
    ],
    highlights: [
      { title: 'Multi-Agent LangGraph Workflow', text: 'Contributed to an 8-node LangGraph state machine that classifies user intent, generates schema-aware SQL, executes queries, selects the right visualisation type, and produces a business interpretation — all autonomously.' },
      { title: '14 Interactive Chart Types', text: 'The system dynamically generates bar charts, line charts, scatter plots, heatmaps, geographical maps, Sankey diagrams, and more — all rendered interactively via Plotly based on the nature of the data returned.' },
      { title: 'Domain-Intelligent SQL Generation', text: 'SQL generation is guided by extensive domain context — including asset condition grading scales, government abbreviations, financial year conventions, and null-filtering rules — to produce reliable, business-accurate queries.' },
      { title: 'AI Business Interpretations', text: 'After every query, the system generates a written business interpretation in either a standard summary or a detailed 5-section analysis covering key findings, comparisons, risk indicators, and actionable recommendations.' },
      { title: 'Multi-LLM Support', text: 'Configurable to run against multiple LLM providers including Azure OpenAI and direct OpenAI models, with support for both standard and reasoning-mode models depending on query complexity.' },
      { title: 'Conversation Context', text: 'The system maintains conversation history, allowing users to ask natural follow-up questions that refine or build upon previous queries without repeating context.' },
    ],
    security: ['Azure Entra ID JWT authentication on all protected routes', 'SQL injection protection with blocked destructive operations', 'Allowed-table whitelist preventing unauthorised data access', 'Query timeouts and row limits to prevent abuse', 'API keys managed via environment variables outside source control'],
  },
  {
    id: 'far',
    title: 'FAR Chatbot',
    type: 'Multi-Service AI Chatbot',
    desc: 'A conversational AI assistant built for the Western Cape Department of Infrastructure. Lets staff query a large government facility dataset — covering schools, clinics, and land assets — using plain English, powered by a LangGraph ReAct agent that translates questions into SQL.',
    tech: ['React', 'TypeScript', 'LangGraph', 'PostgreSQL', 'PGVector', 'Docker', 'Azure'],
    color: '#a78bfa',
    shape: 'icosahedron',
    overview: 'Built collaboratively for the Western Cape Department of Infrastructure. The chatbot gives departmental staff a conversational interface to query the government\'s Facility Asset Register — a large dataset covering schools, clinics, and land parcels across the Western Cape — without needing database access or technical expertise.',
    architecture: [
      { label: 'React 19 Frontend', detail: 'Modern SPA built with Vite and Tailwind CSS 4, featuring a full chat interface, typing animations, model selection, memory toggle, and export to PDF or Word.' },
      { label: 'TypeScript API Gateway', detail: 'Express 5 gateway running on Bun with Entra ID JWT authentication, full chat session management, concurrent request protection, and message persistence.' },
      { label: 'LangGraph ReAct Agent', detail: 'AI reasoning agent that determines when to query the database, constructs safe SQL, retrieves results, and formulates a natural-language response — with full conversation memory.' },
      { label: 'PostgreSQL + Vector Store', detail: 'Relational database storing the facility dataset and chat history, extended with pgvector for optional semantic search capabilities.' },
    ],
    highlights: [
      { title: 'ReAct Agent with SQL Reasoning', text: 'Contributed to a LangGraph ReAct agent that reasons step-by-step about user questions, decides when and how to query the database, and formulates natural-language responses. Supports multiple Azure OpenAI model deployments.' },
      { title: 'Safe Database Querying', text: 'Implemented a SQL execution tool with strict safety controls — only SELECT queries are permitted, dangerous operations are blocked, and results are automatically paginated to prevent overload.' },
      { title: 'Full Chat Session Management', text: 'Built the API layer for creating, listing, renaming, and deleting chat sessions, with message history persisted to PostgreSQL and ownership verification on every request.' },
      { title: 'Rich Frontend Chat Experience', text: 'Implemented word-by-word typing animations, collapsible reference sections, clickable sample questions, auto-resizing inputs, relative timestamps, and export to PDF and Word — all in the React frontend.' },
      { title: 'Shared Monorepo Architecture', text: 'The codebase is structured as a monorepo with a shared package providing database connection management, TypeScript interfaces, and utilities — keeping code consistent across services.' },
      { title: 'Passwordless Cloud Auth', text: 'Implemented Azure Managed Identity for secure, credential-free access to the database and Azure OpenAI — eliminating secrets from the application layer entirely.' },
    ],
    security: ['Microsoft Entra ID JWT validation on all API routes', 'Tenant ID and scope verification per request', 'Chat ownership verified before any data access', 'SQL-level blocking of all destructive operations', 'Azure Managed Identity for credential-free service access'],
  },
]